In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn as sk

READING CSV FILE

In [2]:
df=pd.read_csv(r"C:\Users\Madhu\Documents\IPD_1\titanic.csv")

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.shape

(891, 12)

HANDLING OF DUPLICATES

In [5]:
df.duplicated().sum()

0

DELETING A COLUMN

In [6]:
df.drop(['Cabin'], axis=1, inplace=True)

In [7]:
df.drop(columns= [ 'PassengerId', 'Name' ,'Ticket','Embarked' ],axis=1,inplace=True)

HANDLING OF MISSING VALUES

In [8]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
dtype: int64

In [9]:
df['Age'].mean()

29.69911764705882

In [10]:
def fill_age(row):
    age = row['Age']
    
    if pd.isnull(age):
        return 29.69
    else:
        return age

In [11]:
df['Age'] = df.apply(fill_age, axis=1)

In [12]:
df.shape

(891, 7)

In [13]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
dtype: int64

In [14]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0         0       3    male  22.0      1      0   7.2500
1         1       1  female  38.0      1      0  71.2833
2         1       3  female  26.0      0      0   7.9250
3         1       1  female  35.0      1      0  53.1000
4         0       3    male  35.0      0      0   8.0500

ENCODING

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
dtypes: float64(2), int64(4), object(1)
memory usage: 48.9+ KB


In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
label_encodersg = LabelEncoder()
df['Sex']=label_encodersg.fit_transform(df['Sex'])
import pickle
with open ("tsg.pkl","wb") as file:
    pickle.dump(label_encodersg,file)

In [18]:
df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0         0       3    1  22.0      1      0   7.2500
1         1       1    0  38.0      1      0  71.2833
2         1       3    0  26.0      0      0   7.9250
3         1       1    0  35.0      1      0  53.1000
4         0       3    1  35.0      0      0   8.0500

SPLITING

In [19]:
x=df.drop("Survived",axis=1)
y=df['Survived']

SCALING

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
scaler=StandardScaler()

In [22]:
x_scaled = scaler.fit_transform(x)

TRAIN,TEST AND SPLITING

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [25]:
x_train.head()

Pclass  Sex   Age  SibSp  Parch     Fare
331       1    1  45.5      0      0  28.5000
733       2    1  23.0      0      0  13.0000
382       3    1  32.0      0      0   7.9250
704       3    1  26.0      1      0   7.8542
813       3    0   6.0      4      2  31.2750

In [26]:
x_train.shape

(712, 6)

In [27]:
y_train.shape

(712,)

In [28]:
x_test.shape

(179, 6)

In [29]:
y_test.shape

(179,)

MODEL BUILDING

KNN MODEL

In [30]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
#from sklearn.metrics import accuracy_score


In [31]:
knn1=KNeighborsClassifier()
knn1.fit(x_train,y_train)
predict_knn1=knn1.predict(x_test)
training_accuracy=knn1.score(x_train,y_train)
testing_accuracy=knn1.score(x_test,y_test)
print("*** KNeighborsClassifier ***")
print("Training Accuracy : ",training_accuracy)
print("Testing Accuracy : ",testing_accuracy)
print("Accuracy Score : ",accuracy_score(y_test,predict_knn1))
print("** Confusion Matrix **")
print(confusion_matrix(y_test,predict_knn1))
print("** Classification Report **")
print(classification_report(y_test,predict_knn1))

*** KNeighborsClassifier ***
Training Accuracy :  0.7963483146067416
Testing Accuracy :  0.6983240223463687
Accuracy Score :  0.6983240223463687
** Confusion Matrix **
[[85 20]
 [34 40]]
** Classification Report **
              precision    recall  f1-score   support

           0       0.71      0.81      0.76       105
           1       0.67      0.54      0.60        74

    accuracy                           0.70       179
   macro avg       0.69      0.68      0.68       179
weighted avg       0.69      0.70      0.69       179



LOGISTIC REGRESSION

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
def Logistic(x_train,x_test,y_train,y_test):
    lgr=LogisticRegression()
    logistic=lgr.fit(x_train,y_train)
    predict_logistic=logistic.predict(x_test)
    training_accuracy=logistic.score(x_train,y_train)
    testing_accuracy=logistic.score(x_test,y_test)
    print("*** Logistic Regression ***")
    print("Training Accuracy : ",training_accuracy)
    print("Testing Accuracy : ",testing_accuracy)
    print("Accuracy Score : ",accuracy_score(y_test,predict_logistic))
    print("** Confusion Matrix **")
    print(confusion_matrix(y_test,predict_logistic))
    print("** Classification Report **")
    print(classification_report(y_test,predict_logistic))

In [34]:
Logistic(x_train,x_test,y_train,y_test)

*** Logistic Regression ***
Training Accuracy :  0.800561797752809
Testing Accuracy :  0.8100558659217877
Accuracy Score :  0.8100558659217877
** Confusion Matrix **
[[92 13]
 [21 53]]
** Classification Report **
              precision    recall  f1-score   support

           0       0.81      0.88      0.84       105
           1       0.80      0.72      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179



RANDOM FOREST

In [35]:
from sklearn.ensemble import RandomForestClassifier
rdf=RandomForestClassifier()

In [37]:
def Random_Forest(x_train,x_test,y_train,y_test):
    radf=RandomForestClassifier()
    radf.fit(x_train,y_train)
    predict_random=radf.predict(x_test)
    training_accuracy=radf.score(x_train,y_train)
    testing_accuracy=radf.score(x_test,y_test)
    print("*** Random Forest ***")
    print("Training Accuracy : ",training_accuracy)
    print("Testing Accuracy : ",testing_accuracy)
    print("Accuracy Score : ",accuracy_score(y_test, predict_random))
    print("** Confusion Matrix **")
    print(confusion_matrix(y_test, predict_random))
    print("** Classification Report **")
    print(classification_report(y_test, predict_random))

In [38]:
Random_Forest(x_train,x_test,y_train,y_test)

*** Random Forest ***
Training Accuracy :  0.9803370786516854
Testing Accuracy :  0.7877094972067039
Accuracy Score :  0.7877094972067039
** Confusion Matrix **
[[90 15]
 [23 51]]
** Classification Report **
              precision    recall  f1-score   support

           0       0.80      0.86      0.83       105
           1       0.77      0.69      0.73        74

    accuracy                           0.79       179
   macro avg       0.78      0.77      0.78       179
weighted avg       0.79      0.79      0.79       179



DECISION TREE

In [39]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
def DecisionTree(x_train, x_test, y_train, y_test):
    dt_classifier = DecisionTreeClassifier(criterion='entropy', max_depth=3)
    decision_tree = dt_classifier.fit(x_train, y_train)
    predict_decision_tree = decision_tree.predict(x_test)
    training_accuracy = decision_tree.score(x_train, y_train)
    testing_accuracy = decision_tree.score(x_test, y_test)

    print("*** Decision Tree Classifier ***")
    print("Training Accuracy:", training_accuracy)
    print("Testing Accuracy:", testing_accuracy)
    print("Accuracy Score:", accuracy_score(y_test, predict_decision_tree))
    print("** Confusion Matrix **")
    print(confusion_matrix(y_test, predict_decision_tree))
    print("** Classification Report **")
    print(classification_report(y_test, predict_decision_tree))

# Example usage:
DecisionTree(x_train, x_test, y_train, y_test)

*** Decision Tree Classifier ***
Training Accuracy: 0.8342696629213483
Testing Accuracy: 0.7988826815642458
Accuracy Score: 0.7988826815642458
** Confusion Matrix **
[[92 13]
 [23 51]]
** Classification Report **
              precision    recall  f1-score   support

           0       0.80      0.88      0.84       105
           1       0.80      0.69      0.74        74

    accuracy                           0.80       179
   macro avg       0.80      0.78      0.79       179
weighted avg       0.80      0.80      0.80       179



CROSS VALIDATION AMONG ALL

In [40]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

# Cross-validation for K-Nearest Neighbors (KNN)
knn1 = KNeighborsClassifier()
knn_cv_scores = cross_val_score(knn1, x, y, cv=5)
print("K-Nearest Neighbors (KNN) Cross-Validation Scores:", knn_cv_scores)
print("Mean Accuracy:", knn_cv_scores.mean())

# Cross-validation for Logistic Regression
lgr = LogisticRegression()
lgr_cv_scores = cross_val_score(lgr, x, y, cv=5)
print("Logistic Regression Cross-Validation Scores:", lgr_cv_scores)
print("Mean Accuracy:", lgr_cv_scores.mean())

# Cross-validation for Random Forest
radf = RandomForestClassifier()
rf_cv_scores = cross_val_score(radf, x, y, cv=5)
print("Random Forest Cross-Validation Scores:", rf_cv_scores)
print("Mean Accuracy:", rf_cv_scores.mean())

# Cross-validation for Decision Tree
dt = DecisionTreeClassifier()
dt_cv_scores = cross_val_score(dt, x, y, cv=5)
print("Decision Tree Cross-Validation Scores:", dt_cv_scores)
print("Mean Accuracy:", dt_cv_scores.mean())

K-Nearest Neighbors (KNN) Cross-Validation Scores: [0.63687151 0.67977528 0.73595506 0.7247191  0.70786517]
Mean Accuracy: 0.6970372230242923
Logistic Regression Cross-Validation Scores: [0.7877095  0.7752809  0.78089888 0.76404494 0.81460674]
Mean Accuracy: 0.7845081915761722
Random Forest Cross-Validation Scores: [0.77094972 0.81460674 0.87078652 0.7752809  0.83707865]
Mean Accuracy: 0.813740505931831
Decision Tree Cross-Validation Scores: [0.72067039 0.79213483 0.82022472 0.74719101 0.80337079]
Mean Accuracy: 0.7767183478752119


RANDOM FOREST HAS BETTER ACCURACY SO SELECTING RANDOM FOREST

SAVING

In [41]:
from sklearn.ensemble import RandomForestClassifier
radf.fit(x_train, y_train)
predictions = radf.predict(x_test)

In [42]:
import pickle 
with open("radf.pkl", 'wb') as file:
    pickle.dump(radf, file)

In [43]:
df.head(2)

Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0         0       3    1  22.0      1      0   7.2500
1         1       1    0  38.0      1      0  71.2833

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int32  
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
dtypes: float64(2), int32(1), int64(4)
memory usage: 45.4 KB


In [45]:
Pclass=1
Sex=0
Age=38
SibSp=1
Parch=0
Fare=71.28

Pclass=1
Sex=0
Age=38
SibSp=1
Parch=0
Fare=71.28


names=[Pclass,Sex,Age,SibSp,Parch,Fare]

prediction=radf.predict([names])
print(prediction)
prediction = int(prediction)
print(type(prediction))
names=[Pclass,Sex,Age,SibSp,Parch,Fare]

prediction=radf.predict([names])
print(prediction)
prediction = int(prediction)
print(type(prediction))

[1]
<class 'int'>
[1]
<class 'int'>


C:\Users\Madhu\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
C:\Users\Madhu\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
